-- Expand plant safety catalog (curated ASPCA-class guidance — not vet diagnosis).
-- Idempotent upsert by latin. Run after 20260321220000_plant_safety.sql.

insert into public.plants (latin, name_uk, name_en, name_pl, aliases) values
  ('Ficus elastica', 'Фікус каучуконосний', 'Rubber plant', 'Fikus sprężysty', array['rubber plant', 'фікус', 'каучукове дерево']),
  ('Ficus benjamina', 'Фікус Бенджаміна', 'Weeping fig', 'Fikus benjamina', array['weeping fig', 'benjamin fig', 'бенджамін']),
  ('Hedera helix', 'Плющ звичайний', 'English ivy', 'Bluszcz pospolity', array['english ivy', 'ivy', 'плющ']),
  ('Schefflera spp.', 'Шефлера', 'Umbrella plant / schefflera', 'Szeflera', array['umbrella plant', 'шефлера', 'шеффлера']),
  ('Crassula ovata', 'Товстянка / нефритове дерево', 'Jade plant', 'Grubosz jajowaty', array['jade', 'money plant', 'товстянка', 'красула']),
  ('Kalanchoe spp.', 'Каланхое', 'Kalanchoe', 'Kalanchoe', array['kalanchoe', 'каланхое']),
  ('Euphorbia pulcherrima', 'Пуансетія', 'Poinsettia', 'Wilczomlecz piękny', array['poinsettia', 'різдвяна зірка', 'пуансетія']),
  ('Convallaria majalis', 'Конвалія', 'Lily of the valley', 'Konwalia majowa', array['lily of the valley', 'конвалія']),
  ('Taxus baccata', 'Тис', 'Yew', 'Cis pospolity', array['yew', 'тис ягідний']),
  ('Begonia spp.', 'Бегонія', 'Begonia', 'Begonia', array['begonia', 'бегонія']),
  ('Chrysanthemum spp.', 'Хризантема', 'Chrysanthemum', 'Chryzantema', array['mum', 'хризантема']),
  ('Hydrangea spp.', 'Гортензія', 'Hydrangea', 'Hortensja', array['hydrangea', 'гортензія']),
  ('Syngonium podophyllum', 'Сингоніум', 'Arrowhead plant', 'Syngonium', array['arrowhead', 'сингоніум']),
  ('Anthurium spp.', 'Антуріум', 'Anthurium / flamingo flower', 'Anturium', array['anthurium', 'антуріум']),
  ('Alocasia spp.', 'Алоказія', 'Alocasia / elephant ear', 'Alokazja', array['alocasia', 'elephant ear', 'алоказія']),
  ('Solanum lycopersicum', 'Томат (рослина)', 'Tomato plant', 'Pomidor', array['tomato', 'томат', 'помідор']),
  ('Vitis vinifera', 'Виноград', 'Grape / vine', 'Winorośl', array['grape', 'raisin', 'виноград', 'родзинки']),
  ('Allium cepa', 'Цибуля', 'Onion', 'Cebula', array['onion', 'цибуля', 'allium']),
  ('Allium sativum', 'Часник', 'Garlic', 'Czosnek', array['garlic', 'часник']),
  ('Hoya spp.', 'Хойя', 'Hoya / wax plant', 'Hoya', array['hoya', 'wax plant', 'хойя']),
  ('Pilea peperomioides', 'Пілея', 'Chinese money plant', 'Pilea', array['pilea', 'chinese money plant', 'пілея']),
  ('Chamaedorea elegans', 'Хамедорея (парлова пальма)', 'Parlor palm', 'Chamedora wytworna', array['parlor palm', 'хамедорея']),
  ('Aspidistra elatior', 'Аспідістра', 'Cast iron plant', 'Aspidistra', array['cast iron plant', 'аспідістра']),
  ('Haworthia spp.', 'Гавортія', 'Haworthia', 'Haworthia', array['haworthia', 'гавортія']),
  ('Echeveria spp.', 'Ечеверія', 'Echeveria', 'Echeveria', array['echeveria', 'ечеверія', 'сукулент']),
  ('Ocimum basilicum', 'Базилік', 'Basil', 'Bazylia', array['basil', 'базилік']),
  ('Beaucarnea recurvata', 'Бокарнея (кінський хвіст)', 'Ponytail palm', 'Nolina', array['ponytail palm', 'бокарнея', 'ноліна'])
on conflict (latin) do update set
  name_uk = excluded.name_uk,
  name_en = excluded.name_en,
  name_pl = excluded.name_pl,
  aliases = excluded.aliases,
  updated_at = now();

insert into public.plant_toxicity (plant_id, species, level, notes)
select p.id, v.species, v.level, v.notes
from public.plants p
join (
  values
    ('Ficus elastica', 'cat', 'mild', 'Сік може дратувати шкіру/ШКТ при поїданні.'),
    ('Ficus elastica', 'dog', 'mild', 'Сік може дратувати шкіру/ШКТ при поїданні.'),
    ('Ficus benjamina', 'cat', 'mild', 'Може викликати подразнення ШКТ.'),
    ('Ficus benjamina', 'dog', 'mild', 'Може викликати подразнення ШКТ.'),
    ('Hedera helix', 'cat', 'toxic', 'Сапоніни — блювота, діарея, можлива млявість.'),
    ('Hedera helix', 'dog', 'toxic', 'Сапоніни — блювота, діарея, можлива млявість.'),
    ('Schefflera spp.', 'cat', 'toxic', 'Оксалати — подразнення рота, слина, блювання.'),
    ('Schefflera spp.', 'dog', 'toxic', 'Оксалати — подразнення рота, слина, блювання.'),
    ('Crassula ovata', 'cat', 'toxic', 'Може викликати блювання й млявість.'),
    ('Crassula ovata', 'dog', 'toxic', 'Може викликати блювання й млявість.'),
    ('Kalanchoe spp.', 'cat', 'toxic', 'Кардіоглікозиди — ШКТ і ризик для серця.'),
    ('Kalanchoe spp.', 'dog', 'toxic', 'Кардіоглікозиди — ШКТ і ризик для серця.'),
    ('Euphorbia pulcherrima', 'cat', 'mild', 'Зазвичай легке подразнення рота/ШКТ.'),
    ('Euphorbia pulcherrima', 'dog', 'mild', 'Зазвичай легке подразнення рота/ШКТ.'),
    ('Convallaria majalis', 'cat', 'toxic', 'Кардіотоксична — усі частини; терміново до вета.'),
    ('Convallaria majalis', 'dog', 'toxic', 'Кардіотоксична — усі частини; терміново до вета.'),
    ('Taxus baccata', 'cat', 'toxic', 'Дуже небезпечна — серце; терміново до вета.'),
    ('Taxus baccata', 'dog', 'toxic', 'Дуже небезпечна — серце; терміново до вета.'),
    ('Begonia spp.', 'cat', 'toxic', 'Оксалати (особливо бульби/корені) — подразнення.'),
    ('Begonia spp.', 'dog', 'toxic', 'Оксалати (особливо бульби/корені) — подразнення.'),
    ('Chrysanthemum spp.', 'cat', 'toxic', 'Може викликати блювання, діарею, дерматит.'),
    ('Chrysanthemum spp.', 'dog', 'toxic', 'Може викликати блювання, діарею, дерматит.'),
    ('Hydrangea spp.', 'cat', 'toxic', 'Ціаногенні глікозиди — блювота, діарея.'),
    ('Hydrangea spp.', 'dog', 'toxic', 'Ціаногенні глікозиди — блювота, діарея.'),
    ('Syngonium podophyllum', 'cat', 'toxic', 'Оксалати — подразнення рота й блювання.'),
    ('Syngonium podophyllum', 'dog', 'toxic', 'Оксалати — подразнення рота й блювання.'),
    ('Anthurium spp.', 'cat', 'toxic', 'Оксалати — біль у роті, слина, блювання.'),
    ('Anthurium spp.', 'dog', 'toxic', 'Оксалати — біль у роті, слина, блювання.'),
    ('Alocasia spp.', 'cat', 'toxic', 'Оксалати — сильне подразнення слизових.'),
    ('Alocasia spp.', 'dog', 'toxic', 'Оксалати — сильне подразнення слизових.'),
    ('Solanum lycopersicum', 'cat', 'toxic', 'Зелені частини / незрілі плоди — соланін.'),
    ('Solanum lycopersicum', 'dog', 'toxic', 'Зелені частини / незрілі плоди — соланін.'),
    ('Vitis vinifera', 'cat', 'toxic', 'Ризик для нирок; уникати навіть малих кількостей.'),
    ('Vitis vinifera', 'dog', 'toxic', 'Токсичність для собак — нирки; терміново до вета.'),
    ('Allium cepa', 'cat', 'toxic', 'Ушкоджує еритроцити — навіть у їжі/юшці.'),
    ('Allium cepa', 'dog', 'toxic', 'Ушкоджує еритроцити — навіть у їжі/юшці.'),
    ('Allium sativum', 'cat', 'toxic', 'Як і цибуля — ризик гемолізу.'),
    ('Allium sativum', 'dog', 'toxic', 'Як і цибуля — ризик гемолізу.'),
    ('Hoya spp.', 'cat', 'safe', 'Зазвичай вважається безпечною.'),
    ('Hoya spp.', 'dog', 'safe', 'Зазвичай вважається безпечною.'),
    ('Pilea peperomioides', 'cat', 'safe', 'Зазвичай безпечна.'),
    ('Pilea peperomioides', 'dog', 'safe', 'Зазвичай безпечна.'),
    ('Chamaedorea elegans', 'cat', 'safe', 'Зазвичай безпечна.'),
    ('Chamaedorea elegans', 'dog', 'safe', 'Зазвичай безпечна.'),
    ('Aspidistra elatior', 'cat', 'safe', 'Зазвичай безпечна.'),
    ('Aspidistra elatior', 'dog', 'safe', 'Зазвичай безпечна.'),
    ('Haworthia spp.', 'cat', 'safe', 'Зазвичай безпечна.'),
    ('Haworthia spp.', 'dog', 'safe', 'Зазвичай безпечна.'),
    ('Echeveria spp.', 'cat', 'safe', 'Зазвичай безпечна.'),
    ('Echeveria spp.', 'dog', 'safe', 'Зазвичай безпечна.'),
    ('Ocimum basilicum', 'cat', 'safe', 'Кулинарні кількості зазвичай ок.'),
    ('Ocimum basilicum', 'dog', 'safe', 'Кулинарні кількості зазвичай ок.'),
    ('Beaucarnea recurvata', 'cat', 'safe', 'Зазвичай безпечна.'),
    ('Beaucarnea recurvata', 'dog', 'safe', 'Зазвичай безпечна.')
) as v(latin, species, level, notes) on p.latin = v.latin
on conflict (plant_id, species) do update set
  level = excluded.level,
  notes = excluded.notes;
